name: Publish roadmap
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build roadmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          cd $GITHUB_WORKSPACE
          composer install
          ./build.sh
      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.connectionString }}
        run: |
          cd $GITHUB_WORKSPACE/docs
          az storage blob upload-batch \
                            -s ./site \
                            -d 'https://fireflyiiidocs.blob.core.windows.net/$web' \
                            --no-progress \
                            --overwrite
