name: Publish roadmap
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update repository
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "robot@firefly-iii.org"
          git config user.name "Firefly III build robot"
          echo $(date '+%d-%m-%Y %T %Z') > date.txt
          git add date.txt
          git commit -m "Auto commit on $(date '+%d-%m-%Y') [skip ci]"
          git push
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Build roadmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ./build.sh
          cp -r .well-known build/.well-known
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: aaf8eef9dd565a13de210d18c7462092
          projectName: roadmap
          directory: build
          wranglerVersion: '3'
