name: Publish roadmap
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build roadmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.connectionString }}
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ./build.sh
          ls dist
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: $web
          connection_string: ${{ secrets.connectionString }}
          extra_args: '--no-progress --overwrite'
          overwrite: 'true'
