name: Transfer issues

on:
  issues:
    types:
      - opened

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          router: holla:firefly-iii
          apply_label: "Needs Triage:FF0000"
          create_stub: false
